# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19PlIU96bqEzFokjzdaxMslQlV6DZ0jZ_
"""

from distutils.core import setup

setup(
   name='timeSeriesHelper',
   version='1.0',
   description='A module help with data inspection, cleaning, identifying and filling missing time steps for time series analysis',
   author='Miao Xi',
   author_email='miao.xi@mail.utoronto.ca',
)